export const MOVIES_GET_SUCCESS = 'ITEMS_GET_SUCCESS';
export const MOVIES_GET_ERROR = 'ITEMS_GET_ERROR';
export const MOVIES_UPDATED = 'ITEMS_UPDATED';
export const FIND_MOVIE_GET_SUCESS = 'FIND_MOVIE_GET_SUCESS';
export const SORT_MOVIES_BY_KEY = 'SORT_MOVIES_BY_KEY';
export const RATE_MOVIE = 'RATE_MOVIE';

export const USER_UPDATED = 'USER_UPDATED';
